### ISSUE TITLE
不能接收机器人账号本人的群消息

### ISSUE THREAD

**Issue by kiprunning** [pig6/wxrobot#16]
@bot.register(Group, PICTURE)
def recv_image(msg):
  pass

代码如上，不能收到机器人微信账号发送的图片消息。这个调试程序不太方便，还是有别的配置可以设置呢？

**Comment by pig6** [comment]
是否能描述清楚一些？

**Comment by kiprunning** [comment]
> 是否能描述清楚一些？
嗯，是有一个开关没有加：except_self=False
