### ISSUE TITLE
KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by YungRun** [pig6/wxrobot#6]
env：
Docker version 
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Image: python:3.7

Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "robot.py", line 10, in <module>
    bot = Bot(cache_path=True, console_qr=True)
  File "/usr/local/lib/python3.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.7/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by huleski** [comment]
你可以试着登录[网页微信](https://wx.qq.com/)
如果返回信息是:
```html
<error>
	<ret>1203</ret>
	<message>
		为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
	</message>
</error>
```
那么运行该项目就会报错:` pass_ticket`
应该是处于安全考虑, 新申请的微信是无法登录网页微信的, 然而这个程序就是用到了网页微信的接口 #

**Comment by YungRun** [comment]
确实是禁止网页登录这个原因，谢谢了
